In [ ]:
import numpy as np

### Basics of an array

In [ ]:
# First axis is row, second axis is column.
# First axis has length of 2 (2 rows), second axis has length of 3 (3 columns)
[[1., 0., 6.],
 [2., 4., 3.]]

[[1.0, 0.0, 6.0], [2.0, 4.0, 3.0]]

In [ ]:
# To create a NumPy array, create a Python array then pass it to np.array
array = [[1,2],
         [3,0],
         [0,6]]

init_numpy_array = np.array(array)
float_numpy_array = np.array(array, dtype=np.float) # set data type while creating an array
string_numpy_array = np.array(array, dtype=np.str)
boolean_numpy_array = np.array(array, dtype=np.bool)

print("__init_numpy_array__")
print(init_numpy_array)
print("__float_numpy_array__")
print(float_numpy_array)
print("__string_numpy_array__")
print(string_numpy_array)
print("__boolean_numpy_array__")
print(boolean_numpy_array)  # True for non-zero, False for zero


__init_numpy_array__
[[1 2]
 [3 0]
 [0 6]]
__float_numpy_array__
[[1. 2.]
 [3. 0.]
 [0. 6.]]
__string_numpy_array__
[['1' '2']
 ['3' '0']
 ['0' '6']]
__boolean_numpy_array__
[[ True  True]
 [ True False]
 [False  True]]


In [ ]:
# Getting some attributes of an array

print("Type of array: ", init_numpy_array.dtype)
print("Number of dimensions: ", init_numpy_array.ndim)
print("Shape of array: ", init_numpy_array.shape)
print("Size of array: ", init_numpy_array.size) # size is total items count, regardless of shape


Type of array:  int64
Number of dimensions:  2
Shape of array:  (3, 2)
Size of array:  6


In [ ]:
# Running basic mathematical functions on arrays

array = np.array([[1,2],
                  [3,0],
                  [0,6]])
print("__array__")
print(array)

print("Total sum: ", array.sum())
print("Total mean: ", array.mean())
print("Total std: ", array.std())
print("Total min: ", array.min())
print("Total max: ", array.max())
print("Total cumsum: ", array.cumsum())

print("___")

print("Sum over rows: ", array.sum(axis=0))
print("Sum over cols: ", array.sum(axis=1))
print("Sum first col: ", array[:,0].sum())

print("___")

print("Argmax flat: ", np.argmax(array)) # Return index of max element in an array (not the element)
print("Argmax row: ", np.argmax(array, axis=0)) # Return index of max element of cols between rows
print("Argmax col: ", np.argmax(array, axis=1)) # Return index of max element of rows between cols

print("Max value: ", np.amax(array))  # Return max element in entire array
print("Max value in rows: ", np.amax(array, axis=0)) # Return max element in rows
print("Max value in cols: ", np.amax(array, axis=1)) # Return max elements in cols

# Argmin and amin are function for finding min index and min value


__array__
[[1 2]
 [3 0]
 [0 6]]
Total sum:  12
Total mean:  2.0
Total std:  2.0816659994661326
Total min:  0
Total max:  6
Total cumsum:  [ 1  3  6  6  6 12]
___
Sum over rows:  [4 8]
Sum over cols:  [3 3 6]
Sum first col:  4
___
Argmax flat:  5
Argmax row:  [1 2]
Argmax col:  [1 0 1]
Max value:  6
Max value in rows:  [3 6]
Max value in cols:  [2 3 6]


In [ ]:
# Change the data dtype of existing NumPy array

array = np.array([[1,2],
                  [3,0],
                  [0,6]])

print("Current data type :", array.dtype)

# Change the type to float
float_array = array.astype(np.float)
print("Float data type :", float_array.dtype)

# Change the type to string
string_array = array.astype(np.str)
print("String data type :", string_array.dtype)


Current data type : int64
Float data type : float64
String data type : <U21


In [ ]:
# Create a NumPy range of numbers. np.arange(start, stop, step, dtype)

range_1 = np.arange(0, 10, 1) # stop (10) is excluded
print("Range 1: ", range_1)

range_2 = np.arange(10)  # same as range_1, defaul start is 0, defautl step is 1
print("Range 2: ", range_2)

range_3 = np.arange(10, 0, -1) # reverse order
print("Range 3: ", range_3)

range_4 = np.arange(1.1, 4.3, .3) # range with float numbers
print("Range 4: ", range_4)

# Create evenly spaced numbers over a specified interval
linspace_1 = np.linspace(0, 10, 5) # (start, stop, number of samples)
print("Llinspace 1 :", linspace_1)

linspace_2 = np.linspace(1.1, 4.3, 10) # 10 numbers starting 1.1 and ending 4.3
print("Llinspace 2 :", linspace_2)


Range 1:  [0 1 2 3 4 5 6 7 8 9]
Range 2:  [0 1 2 3 4 5 6 7 8 9]
Range 3:  [10  9  8  7  6  5  4  3  2  1]
Range 4:  [1.1 1.4 1.7 2.  2.3 2.6 2.9 3.2 3.5 3.8 4.1]
Llinspace 1 : [ 0.   2.5  5.   7.5 10. ]
Llinspace 2 : [1.1        1.45555556 1.81111111 2.16666667 2.52222222 2.87777778
 3.23333333 3.58888889 3.94444444 4.3       ]


In [ ]:
# Create a zeros array, all values are zero
zeors_array = np.zeros((3,4)) # shape of 3,4
print("__zeors_array__")
print(zeors_array)

# Create an ones array, all values are one
ones_array = np.ones((3,4)) # shape of 3,4
print("__ones_array__")
print(ones_array)

# Create an empty array, all values are some random number to be replaced later
empty_array = np.empty((3,4)) # shape of 3,4
print("__empty_array__")
print(empty_array)

# Create a full array, all values are set to value you set
full_array = np.full((3,4), 44) # shape of 3,4. Set value 44
print("__full_array__")
print(full_array)
full_array_bool = np.full((3,4), False) # shape of 3,4. Set value False
print("__full_array_bool__")
print(full_array_bool)

# Create a full_like array, all values are set to value you set, but shape is same as given array
full_like_array = np.full_like(array, 22) # shape same as given array, all values 22
print("__full_like_array__")
print(full_like_array)

# Create a tile array, all values are set to value you set
tile_array = np.tile(3, 4) # repeat value 3 for 4 times
print("__tile_array__")
print(tile_array)
tile_array_2 = np.tile(3, (5,4)) # repeat 3, in the shape 5,4. Value can also be an array to repeat
print("__tile_array_2__")
print(tile_array_2)

# Create repeat array, all values are set to value you set
repeat_array = np.repeat([1,2,3], 4) # repeat each item for 4 times.
print("__repeat_array__")
print(repeat_array)
print("__tile_array_of_a_list__")
print(np.tile([1,2,3], 3))       # compare this with `repeat_array`, it repeats the list for 3 times

print("___")

print("__array__")
print(array)
print("__repeat_each_row__")
repeat_each_row = np.repeat(array, 2, axis=0) # repeat each row (axis=0) 2 times
print(repeat_each_row)
print("__repeat_each_col__")
repeat_each_col = np.repeat(array, 2, axis=1) # repeat each col (axis=1) 2 times
print(repeat_each_col)


__zeors_array__
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
__ones_array__
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
__empty_array__
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
__full_array__
[[44 44 44 44]
 [44 44 44 44]
 [44 44 44 44]]
__full_array_bool__
[[False False False False]
 [False False False False]
 [False False False False]]
__full_like_array__
[[22 22]
 [22 22]
 [22 22]]
__tile_array__
[3 3 3 3]
__tile_array_2__
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
__repeat_array__
[1 1 1 1 2 2 2 2 3 3 3 3]
__tile_array_of_a_list__
[1 2 3 1 2 3 1 2 3]
___
__array__
[[1 2]
 [3 0]
 [0 6]]
__repeat_each_row__
[[1 2]
 [1 2]
 [3 0]
 [3 0]
 [0 6]
 [0 6]]
__repeat_each_col__
[[1 1 2 2]
 [3 3 0 0]
 [0 0 6 6]]


In [ ]:
# Create an identity array: 2-D array with ones on the diagonal and zeros elsewhere
identity_array = np.identity(4) # only one dimension given
print("__identity_array__")
print(identity_array)

# Create an eye array: 2-D array with ones on the diagonal and zeros elsewhere, shape can be anything
# If K=0 and shape is same for each dimension, eye is same as identity
upper_eye_array = np.eye(3,4, k=1) # shape of (3,4). K positive for upper ones
print("__upper_eye_array__")
print(upper_eye_array)
lower_eye_array = np.eye(3,4, k=-1) # shape of (3,4). K positive for lower ones
print("__lower_eye_array__")
print(lower_eye_array)



__identity_array__
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
__upper_eye_array__
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
__lower_eye_array__
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
# Copy vs view of an array
A = np.array([[1,2],
                  [3,0],
                  [0,6]])
print("__A__")
print(A)

# This is not a copy. B is just another name for A not a new array
B = A
print("__B_is_A__")
print("B is A?: ", B is A)
print("B share memory with A: ", np.shares_memory(A, B))

# Changing B will change A as well
B[0,0] = 1000
print("__updated_A__")
print(A)

# To make a new array you can use .copy(). Updating C does not update A.
C = A.copy()
print("__C__")
print(C)
print("C is A?: ", C is A)
print("C share memory with A: ", np.shares_memory(A, C))



__A__
[[1 2]
 [3 0]
 [0 6]]
__B_is_A__
B is A?:  True
B share memory with A:  True
__updated_A__
[[1000    2]
 [   3    0]
 [   0    6]]
__C__
[[1000    2]
 [   3    0]
 [   0    6]]
C is A?:  False
C share memory with A:  False


### Random array

In [ ]:
# Generate some random arrays

# Construct a new Generator with the default BitGenerator (PCG64).
random_generator = np.random.default_rng(seed=1)
print("__random_array__")
print(random_generator.random((4,3))) # random array shape 4,3

print("__random_array__")
print(np.random.rand(4,3))

# Return a samples from the "standard normal" distribution
print("__random_normal_array_1__")
print(np.random.randn(4,3))

# Draw random samples from a normal (Gaussian) distribution
print("__random_normal_array_2__")
print(np.random.normal(size=10, loc=3, scale=.2)) # 10 points with mean of 3 and with std of 0.2

print("__random_init_array_1__")
print(np.random.randint(2, 8, size=10)) # low=2, high=8, size is shape

print("__random_init_array_2__")
print(np.random.randint(2, 8, size=(4,3))) # low=2, high=8, size is shape

print("__random_init_array_3__")
print(np.random.randint(8, size=(4,3))) # low=0, high=8, size is shape


__random_array__
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
__random_array__
[[0.13125426 0.76558875 0.92163279]
 [0.85965555 0.60504508 0.99208754]
 [0.31149952 0.83830594 0.82814844]
 [0.63133765 0.79802764 0.79872472]]
__random_normal_array_1__
[[-2.02725588 -1.91725921 -2.26475291]
 [-0.24019159 -0.35239181  0.51650522]
 [ 0.49097254  0.93025098  0.84880112]
 [-0.14632408 -0.48857646 -0.33392866]]
__random_normal_array_2__
[3.1939988  2.87003446 2.83742667 3.0200198  3.07124875 3.02254081
 3.10035553 2.9707152  3.05781803 3.03399613]
__random_init_array_1__
[5 7 4 4 6 7 7 2 5 4]
__random_init_array_2__
[[4 5 4]
 [3 7 6]
 [4 2 6]
 [2 3 4]]
__random_init_array_3__
[[3 5 1]
 [7 0 6]
 [2 6 3]
 [2 6 7]]


### Basic Operations

In [ ]:
A = np.arange(0,4)
B = np.arange(5,9)
print("__A__")
print(A)
print("__B__")
print(B)

# Adding to new variable creates a new copy of data, does not change original arrays
C = A + B  # A and B has to be same shape, or refer to broadcasting section.
print("__A+B__")
print(C)           # same as np.add(A,B). For subtract use np.subtract(A,B)
print("A and C share memory: ", np.shares_memory(C, A)) # C and A are different arrays in memory

C = A * B * np.sin(A)
print("__A*B*np.sin(A)__")
print(C)

# Dot product of two arrays. Specifically.
C = A @ B
print("__A@B__")
print(C)

# Calculate exponential of all elements
print("__exp(A)__")
print(np.exp(A))

# Calculate non-negative square-root of all elements
print("__sqrt(A)__")
print(np.sqrt(A))

# Operations bellow happen in-place, means it changes the original array
A+=B
print("__A+=B__")
print(A)   # array A has changed forever, not a view anymore

A*=B
print("__A*=B__")
print(A)   # array A has changed forever, not a view anymore

A//=B
print("__A//=B__")
print(A)   # array A has changed forever, not a view anymore


__A__
[0 1 2 3]
__B__
[5 6 7 8]
__A+B__
[ 5  7  9 11]
A and C share memory:  False
__A*B*np.sin(A)__
[ 0.          5.04882591 12.73016398  3.38688019]
__A@B__
44
__exp(A)__
[ 1.          2.71828183  7.3890561  20.08553692]
__sqrt(A)__
[0.         1.         1.41421356 1.73205081]
__A+=B__
[ 5  7  9 11]
__A*=B__
[25 42 63 88]
__A//=B__
[ 5  7  9 11]


### Flattening array

In [ ]:
array = np.array([[1,2],
                  [3,0],
                  [0,6]])
print("__array__")
print(array)

print("__flat_array__")
print([each for each in array.flat]) # A 1-D iterator over the array

print("__flatten_array__")
print(array.flatten())   # Return a copy of the array collapsed into one dimension.
                         # Note: a new copy being put in memory. Not just a view.
print("Share memory with array: ", np.shares_memory(array.flatten(), array))

print("__ravel_array__")
print(np.ravel(array))   # just a flat view, does not create a new copy

print("Share memory with array: ", np.shares_memory(np.ravel(array), array))

print("__flat_non-zero_indexes__")
print(np.flatnonzero(array))    # Return indexes of non-zero itmes in flat format
print("__non-zero_elements__")
print(np.ravel(array)[np.flatnonzero(array)])


__array__
[[1 2]
 [3 0]
 [0 6]]
__flat_array__
[1, 2, 3, 0, 0, 6]
__flatten_array__
[1 2 3 0 0 6]
Share memory with array:  False
__ravel_array__
[1 2 3 0 0 6]
Share memory with array:  True
__flat_non-zero_indexes__
[0 1 2 5]
__non-zero_elements__
[1 2 3 6]


### Indexing, Slicing and iterating

In [ ]:
array = np.array([[1,2,3],
                  [3,0,4],
                  [0,6,5]])
print("__array__")
print(array)

# If 1D array then: array[index]
# If 2D array then: array[row_filter, col_filterstep]  separated with comma
# If 3D array[sheet_filter, row_filter, col_filter]
# If any dimension not mentioned means all of that dimension:
#    array[3] mean row index 2 and all columns, same as array[3,:]

# If 2D: array[start_row : stop_row : step_row , start_col : stop_col, step_col ]

# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
#    array[0] this means all columns in first row same as array[0, :]

print("__slice_1__")
print(array[0,1])   # get first row (index 0) and second col (index 1)

print("__slice_2__")
print(array[0])   # get first row (index 0) and all columns, same as array[0,:]

print("__slice_3__")
print(array[:,1])   # get all rows and second col (index 1)

print("__slice_4__")
print(array[0:2,1]) # get first and second row and second col (index 1)

print("__slice_5__")
print(array[:,-1])  # get all rows and last column

print("__slice_6__")
print(array[:-1])  # get all rows except last row

print("__reverse_array_row__")
print(array[::-1])  # step -1 means move from last to first row

print("__reverse_array_col__")
print(array[:,::-1])  # step -1 means move from last to first col

print("__reverse_array_row_col__")
print(array[::-1,::-1])  # reverse row and column same as np.flip
print("Same as np.flip: ", np.array_equal(np.flip(array), array[::-1, ::-1]))

print("__every_other_element_row__")
print(array[::2])  # every other row

print("__every_other_element_col__")
print(array[:, ::2])  # every other col

print("__transpose_array__")
print(array.T)  # same as np.transpose(array)


__array__
[[1 2 3]
 [3 0 4]
 [0 6 5]]
__slice_1__
2
__slice_2__
[1 2 3]
__slice_3__
[2 0 6]
__slice_4__
[2 0]
__slice_5__
[3 4 5]
__slice_6__
[[1 2 3]
 [3 0 4]]
__reverse_array_row__
[[0 6 5]
 [3 0 4]
 [1 2 3]]
__reverse_array_col__
[[3 2 1]
 [4 0 3]
 [5 6 0]]
__reverse_array_row_col__
[[5 6 0]
 [4 0 3]
 [3 2 1]]
Same as np.flip:  True
__every_other_element_row__
[[1 2 3]
 [0 6 5]]
__every_other_element_col__
[[1 3]
 [3 4]
 [0 5]]
__transpose_array__
[[1 3 0]
 [2 0 6]
 [3 4 5]]


In [ ]:
array = np.array([[1,2,3],
                  [3,0,4],
                  [0,6,5]])
print("__array__")
print(array)

# Slicing using list of rows and cols (2D example). array([list of rows], [list of cols])
print("__slicing_1__")
print(array[[0,1], [1,2]]) # Return (Row 0 and Col 1) and (Row 1 and col 2)

print("__slicing_2__")
print(array[[0,0,2], [1,0,2]]) # Return (Row 0 and Col 1) and (Row 0 and col 0) and (Row 2 and col 2)


# Construct an open mesh from multiple sequences
print("__ix_1__")
print(np.ix_([0,1], [1,2])) # Returns indices of: [[0,1], [0,2], [1,1], [1,2]]
print(array[np.ix_([0,1], [1,2])])
print(array[[0, 0, 1, 1], [1, 2, 1, 2]].reshape(2,2)) # Same as line above

print("__ix_2__")
print(array[np.ix_([0,1], [2,2])])  # Order does not matter, duplication is allowed


__array__
[[1 2 3]
 [3 0 4]
 [0 6 5]]
__slicing_1__
[2 4]
__slicing_2__
[2 1 5]
__ix_1__
(array([[0],
       [1]]), array([[1, 2]]))
[[2 3]
 [0 4]]
[[2 3]
 [0 4]]
__ix_2__
[[3 3]
 [4 4]]


In [ ]:
# Basic vs Advanced Indexing
array = np.array([[1,2,3],
                  [3,13,4],
                  [0,6,5]])
print("__array__")
print(array)

# Using tuple triggers basic indexing
print("__basic_indexing__")
print(array[(1,1)])

print("__advanced_indexing__")
# Using list triggers basic indexing
print(array[[1,1]])


__array__
[[ 1  2  3]
 [ 3 13  4]
 [ 0  6  5]]
__basic_indexing__
13
__advanced_indexing__
[[ 3 13  4]
 [ 3 13  4]]


In [ ]:
# Array Broadcasting
# Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

A = np.arange(25).reshape(5,5)
B = np.arange(75).reshape(5,5,3)
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

# As you can see shape of A and B are not same, we cannot broadcast them together
# np.add(A, B) will give us an error.
# To solve this we can add another dimension to A using np.newaxis

A = A[:,:, np.newaxis]
print("A new shape: ", A.shape)

# Now we can add two arrays of A and B
print("__A+B__")
print(np.add(A, B))

# Broadcasting is only allowed if two arrays have same dimensions
#    of one dimension is 1 and the other can be any value
# For example: (3,4,1)+(3,4,9) is ok
#              (3,4,2)+(3,4,9) is not ok as third dimension if first array is 2 and second array is 9


Shape of A: (5, 5)
Shape of B: (5, 5, 3)
A new shape:  (5, 5, 1)
__A+B__
[[[ 0  1  2]
  [ 4  5  6]
  [ 8  9 10]
  [12 13 14]
  [16 17 18]]

 [[20 21 22]
  [24 25 26]
  [28 29 30]
  [32 33 34]
  [36 37 38]]

 [[40 41 42]
  [44 45 46]
  [48 49 50]
  [52 53 54]
  [56 57 58]]

 [[60 61 62]
  [64 65 66]
  [68 69 70]
  [72 73 74]
  [76 77 78]]

 [[80 81 82]
  [84 85 86]
  [88 89 90]
  [92 93 94]
  [96 97 98]]]


In [ ]:
# View vs copy of slice of an array
array = np.random.randint(20, size=(4,4))
print("__array__")
print(array)

# Create a new subset of an array
X = array[:2,:2]  # This is only a view. Array X does not exists in the memory, it is reference to array
print("__X__")
print(X)
print("X share memory with array: ", np.shares_memory(X, array))

# Changing value of X does change the origianl array as well
X[0,0] = 100
print("__updated_X__")
print(X)

print("__updated_array__")
print(array)

# To make sure original array does not change then make a copy
Z = array[:2,:2].copy()
Z[1,1] = -9999
print("__Z__")
print(Z)
print("Z share memory with array: ", np.shares_memory(Z, array))

print("__original_array__")
print(array) # The index [1,1] did not change to -9999


__array__
[[ 9 10  3  4]
 [ 3  8 18  3]
 [10 19  9 15]
 [ 9  2  7  3]]
__X__
[[ 9 10]
 [ 3  8]]
X share memory with array:  True
__updated_X__
[[100  10]
 [  3   8]]
__updated_array__
[[100  10   3   4]
 [  3   8  18   3]
 [ 10  19   9  15]
 [  9   2   7   3]]
__Z__
[[  100    10]
 [    3 -9999]]
Z share memory with array:  False
__original_array__
[[100  10   3   4]
 [  3   8  18   3]
 [ 10  19   9  15]
 [  9   2   7   3]]


### Shape Manipulation

In [ ]:
array = np.random.randint(30, size=30)
print("__array__")
print(array)
print("Array shape: ", array.shape)

print("__reshape_1__")
print(array.reshape(6,5))  # Change shape to 6 rows and 5 column. This is just a view.
array = array.reshape(6,5) # This will change the shape of original array

print("__reshape_2__")
print(array.reshape(5,-1))  # Set a dimension to -1 will calculate that dimension automatically: (5,6)

print("__reshape_3__")
print(array.T)       # Transpose replace row and column order
print(array.T.shape)

print("__resize__")
array.resize(3,10)  # Resize will reshape the array permanently (in-place). Resize does not accpet -1 as shape
print(array)


__array__
[ 3 10 22  7  2 28 20 16 21 15  3 17 14 25 13 29 25  0  1 21 27  5 29  4
 19  2 28 18 11  5]
Array shape:  (30,)
__reshape_1__
[[ 3 10 22  7  2]
 [28 20 16 21 15]
 [ 3 17 14 25 13]
 [29 25  0  1 21]
 [27  5 29  4 19]
 [ 2 28 18 11  5]]
__reshape_2__
[[ 3 10 22  7  2 28]
 [20 16 21 15  3 17]
 [14 25 13 29 25  0]
 [ 1 21 27  5 29  4]
 [19  2 28 18 11  5]]
__reshape_3__
[[ 3 28  3 29 27  2]
 [10 20 17 25  5 28]
 [22 16 14  0 29 18]
 [ 7 21 25  1  4 11]
 [ 2 15 13 21 19  5]]
(5, 6)
__resize__
[[ 3 10 22  7  2 28 20 16 21 15]
 [ 3 17 14 25 13 29 25  0  1 21]
 [27  5 29  4 19  2 28 18 11  5]]


### Stacking and Splitting

In [ ]:
A = np.floor(10 * random_generator.random((2,2)))
B = np.floor(10 * random_generator.random((2,2)))
print("__A__")
print(A)
print("__B__")
print(B)

# Split an array into multiple sub-arrays vertically (row-wise)
print("__vstack__")
print(np.vstack((A, B)))

# Split an array into multiple sub-arrays horizontally (column-wise)
print("__hstack__")
print(np.hstack((A, B)))

# Use concatenate to join a sequence of arrays along an existing axis, good for 3D and above
print("__concatenate__")
print(np.concatenate((A,B), axis=0))  # same as vstack in this case

print("__concatenate__")
print(np.concatenate((A,B), axis=1))  # same as hstack in this case


__A__
[[3. 7.]
 [3. 4.]]
__B__
[[1. 4.]
 [2. 2.]]
__vstack__
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]]
__hstack__
[[3. 7. 1. 4.]
 [3. 4. 2. 2.]]
__concatenate__
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]]
__concatenate__
[[3. 7. 1. 4.]
 [3. 4. 2. 2.]]


In [ ]:
array = np.floor(10 * random_generator.random((4,12)))
print('__array__')
print(array)

print("__vsplit_1__")
print(np.vsplit(array, 2))  # split to two arrays by rows
# cannot split by 3 because array split does not result in an equal division
# cannot split by 5 because only has 4 rows
print("__vsplit_2__")
print(np.vsplit(array, 4))  # split to four arrays by rows, each row is new array

print("__vsplit_3__")
print(np.vsplit(array, (1,2)))  # split by row 1, by row 2 and rest of rows. Total three arrays

print("__hsplit_1__")
print(np.hsplit(array, (3,5)))  # split by col 3, by col 5 and rest of cols. Total three arrays

# np.array_split to split an array into multiple sub-arrays.
print("__array_spit_row__")
print(np.array_split(array, 3, axis=0))

print("__array_spit_col__")
print(np.array_split(array, 3, axis=1))


__array__
[[7. 2. 4. 9. 9. 7. 5. 2. 1. 9. 5. 1.]
 [6. 7. 6. 9. 0. 5. 4. 0. 6. 8. 5. 2.]
 [8. 5. 5. 7. 1. 8. 6. 7. 1. 8. 1. 0.]
 [8. 8. 8. 4. 2. 0. 6. 7. 8. 2. 2. 6.]]
__vsplit_1__
[array([[7., 2., 4., 9., 9., 7., 5., 2., 1., 9., 5., 1.],
       [6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.]]), array([[8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.],
       [8., 8., 8., 4., 2., 0., 6., 7., 8., 2., 2., 6.]])]
__vsplit_2__
[array([[7., 2., 4., 9., 9., 7., 5., 2., 1., 9., 5., 1.]]), array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.]]), array([[8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]]), array([[8., 8., 8., 4., 2., 0., 6., 7., 8., 2., 2., 6.]])]
__vsplit_3__
[array([[7., 2., 4., 9., 9., 7., 5., 2., 1., 9., 5., 1.]]), array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.]]), array([[8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.],
       [8., 8., 8., 4., 2., 0., 6., 7., 8., 2., 2., 6.]])]
__hsplit_1__
[array([[7., 2., 4.],
       [6., 7., 6.],
       [8., 5., 5.],
       [8., 

### Sorting an array

In [ ]:
array = np.random.randint(10, size=(4,4))
print('__array__')
print(array)

print("__sort_1__")
print(np.sort(array)) # temporary sort, just a view of sorted array

array.sort()
print("__sorted_array")
print(array)          # in-place sort, it changes the original array

array = np.random.randint(10, size=(4,4))
%time np.sort(array)  # slower
%time array.sort()    # faster

__array__
[[5 2 9 1]
 [7 1 1 1]
 [1 7 3 9]
 [6 7 6 6]]
__sort_1__
[[1 2 5 9]
 [1 1 1 7]
 [1 3 7 9]
 [6 6 6 7]]
__sorted_array
[[1 2 5 9]
 [1 1 1 7]
 [1 3 7 9]
 [6 6 6 7]]
CPU times: user 13 µs, sys: 6 µs, total: 19 µs
Wall time: 18.1 µs
CPU times: user 5 µs, sys: 3 µs, total: 8 µs
Wall time: 10 µs


In [ ]:
# Argsort returns the indices that would sort an array, not the sorted array

scores = np.array([1, 3, 64, 100, 23])
names = np.array(["Jack", "Mark", "David", "Rose", "Sarah"])

# Sort names by their scores
print("__sort_ascending__")
print(names[np.argsort(scores)])

print("__sort_descending__")
print(names[np.argsort(~scores)])      # ~ is Negation
print(names[np.argsort(scores)][::-1]) # this is same as line above


__sort_ascending__
['Jack' 'Mark' 'Sarah' 'David' 'Rose']
__sort_descending__
['Rose' 'David' 'Sarah' 'Mark' 'Jack']
['Rose' 'David' 'Sarah' 'Mark' 'Jack']


### Filtering and searching

In [ ]:
# The function numpy.where can be used to take a boolean-valued array,
#  and produce the tuple of index-arrays that access the True entries of that array, via integer array indexing

array = np.array([[1,2,3],
                  [3,0,4],
                  [0,6,5]])
print("__array__")
print(array)

print("__where_1__")
print(np.where(array>4))         # Returns indicies that meet the condition given
print(array[np.where(array>4)])  # Filter array using output of np.where
print(array[array>4])            # This is same as line above

print("__where_2__")
print(np.where(array>4, array, -1))  # Any element more than 4 keep it, otherwise replace with -1

print("__where_3__")
print(np.where(array>4, True, False))  # Any element more than 4 is True, otherwise is False


__array__
[[1 2 3]
 [3 0 4]
 [0 6 5]]
__where_1__
(array([2, 2]), array([1, 2]))
[6 5]
[6 5]
__where_2__
[[-1 -1 -1]
 [-1 -1 -1]
 [-1  6  5]]
__where_3__
[[False False False]
 [False False False]
 [False  True  True]]


In [ ]:
array = np.array([[2,2,3],
                  [2,0,4],
                  [4,6,5]])

print("__array__")
print(array)

print("__any_1__")
print(np.any(array>3))          # If any element in array has value more than 3

print("__any_row__")
print(np.any(array>3, axis=0))  # If any row has value more than 3

print("__any_col__")
print(np.any(array>3, axis=1))  # If any col has value more than 3


print("__all_1__")
print(np.all(array>3))          # If all element in array has value more than 3

print("__all_row__")
print(np.all(array>1, axis=0))  # If all row has value more than 1

print("__all_col__")
print(np.all(array>3, axis=1))  # If all col has value more than 3


__array__
[[2 2 3]
 [2 0 4]
 [4 6 5]]
__any_1__
True
__any_row__
[ True  True  True]
__any_col__
[False  True  True]
__all_1__
False
__all_row__
[ True False  True]
__all_col__
[False False  True]


In [ ]:
array = np.array([[2,2,3],
                  [2,0,-4],
                  [4,-6,5]])

print("__array__")
print(array)

print("__condition_1__")
print( (array > 1) & (array < 4))  # Only returns boolean based on the conditions (AND)
print(array[(array > 1) & (array < 4)])

print("__condition_2__")
print( (array > 2) | (array > 1))  # Only returns boolean based on the conditions (OR)

print("__condition_3__")
print(array[array<0])              # Filter negative elements



__array__
[[ 2  2  3]
 [ 2  0 -4]
 [ 4 -6  5]]
__condition_1__
[[ True  True  True]
 [ True False False]
 [False False False]]
[2 2 3 2]
__condition_2__
[[ True  True  True]
 [ True False False]
 [ True False  True]]
__condition_3__
[-4 -6]


In [ ]:
array = np.arange(.033333, 0.111133, .001)
print("__array__")
print(array)

# If use filter by exact match for float, there is no match
print("__filtering_float__")
print(array[(array==0.03) | (array==.054)])

print("__filtering_float_isclose__")
# np.isclose returns a boolean array where two arrays are element-wise equal within a tolerance.
print(array[(np.isclose(array, 0.03333, rtol=0.0001)) | (np.isclose(array, 0.08433, rtol=0.0001))])


__array__
[0.033333 0.034333 0.035333 0.036333 0.037333 0.038333 0.039333 0.040333
 0.041333 0.042333 0.043333 0.044333 0.045333 0.046333 0.047333 0.048333
 0.049333 0.050333 0.051333 0.052333 0.053333 0.054333 0.055333 0.056333
 0.057333 0.058333 0.059333 0.060333 0.061333 0.062333 0.063333 0.064333
 0.065333 0.066333 0.067333 0.068333 0.069333 0.070333 0.071333 0.072333
 0.073333 0.074333 0.075333 0.076333 0.077333 0.078333 0.079333 0.080333
 0.081333 0.082333 0.083333 0.084333 0.085333 0.086333 0.087333 0.088333
 0.089333 0.090333 0.091333 0.092333 0.093333 0.094333 0.095333 0.096333
 0.097333 0.098333 0.099333 0.100333 0.101333 0.102333 0.103333 0.104333
 0.105333 0.106333 0.107333 0.108333 0.109333 0.110333]
__filtering_float__
[]
__filtering_float_isclose__
[0.033333 0.084333]
